### PR TITLE
fix: support prepared commit message

### PR DESCRIPTION
**Pull request by incorrupt**
There are two kind of people:

- Those who `git commit`
- Those who `git commit -m`

*cz-customizable* is for those who `git commit`

With this PR, *cz-customizable* is now for everybody!

When used as a git hook, using `git commit -m'my message'` was not making use of `'my message'`. **Now it does.**

This PR adds support for
- **single line** commit messages. The message is passed as the default answer for the `subject` question
- **multi line** commit messages. The first line is passed as the default answer for the `subject`question and the other lines are passed as the default answer for the `body` question

It is non invasive as it is passed as a `default` to enquirer. So the user can just press enter to use it or type another message if he wishes to.

### CODE REVIEW

**Comment by incorrupt** [comment]
@leonardoanalista Build is passing on my fork [Build Status](https://travis-ci.com/incorrupt/cz-customizable)
If you are willing to merge, please do not forget to release a new version!

Thank you

**Comment by leonardoanalista** [comment]
it look like Travis it stuck.. I'l have a loo today ok?

**Comment by leonardoanalista** [comment]
@incorrupt release!

**Comment by incorrupt** [comment]
Cool thank you!

**Comment by axiac** [comment]
This is not a fix, it looks more like a new feature to me. And it breaks the habit to just press `<Enter>` to skip the answer to a question. If I keep pressing `<Enter>` on the question about the long description, it puts there the content of the previous commit message, without empty lines. On each subsequent execution, the message body keeps growing even if I do not enter anything there, just press `<Enter>` as my muscle memory trained during the last 4 years of using Commitizen with this plugin.

The parsing of the commit message body does not take into account the format of the commit message, the same commit message that has been generated by this tool on the previous commit. It includes into the suggested commit body the line `ISSUES CLOSED` that it finds the the previous commit message.

**Comment by leonardoanalista** [comment]
@axiac looking at this again, yes, the prepared commit message breaks the ENTER habit. Please see: https://github.com/leoforfree/cz-customizable/pull/196 @axiac

**Pull request merged**
