### PR TITLE
fix: add option usePreparedCommit default false

### PR DESCRIPTION
**Pull request by leonardoanalista**
fix: add option usePreparedCommit default false

**TODO: it needs unit tests for coverage**

ISSUES CLOSED: #173

### CODE REVIEW

**Comment by jainanuj0812** [comment]
I anybody looking into the lint test issue?

**Comment by leonardoanalista** [comment]
> Can we have this PR merged please

It's just pending unit test coverage. Also considering making this a breaking change since the default is now "false" for usePreparedCommit. Before it was kind of "true". 

I am away this week. I'll be able to write the tests mid-next week.

**Comment by jainanuj0812** [comment]
Sounds good!, thanks man

**Comment by docker-soga** [comment]
This issue has been bothering me, I hope this PR can be merged in time.

**Comment by leonardoanalista** [comment]
@docker-soga I'll try to address the code coverage today so we can merge it. 

I think this is a **breaking change** as it changes the default option.

**Comment by leonardoanalista** [comment]
I am really thinking if we need this option `usePreparedCommit`. I am not sure if people out there use it. We should to deprecate it.

**Review by Scutua — APPROVED** [review]

**Pull request merged**
